default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: test
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: project

test:
  <<: *default
  database: project

production:
  primary: &primary_production
    <<: *default
    database: web
    username: postgres
    password: <%= ENV["WEB_OPS_DATABASE_PASSWORD"] || 'test' %>
    host: localhost
    port: 5432
  cache:
    <<: *primary_production
    database: web_ops_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: web_ops_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: web_ops_production_cable
    migrations_paths: db/cable_migrate
